[monitor:///var/log/auth.log]
disabled = false
index = black_beacon
sourcetype = bb:auth

[monitor:///var/log/syslog]
disabled = false
index = black_beacon
sourcetype = bb:linux

[monitor:///var/log/nginx/access.log]
disabled = false
index = black_beacon
sourcetype = bb:web

[monitor:///opt/black_beacon/data/black_beacon.json]
disabled = false
index = black_beacon
sourcetype = bb:scenario
