[bb:scenario]
SHOULD_LINEMERGE = false
KV_MODE = json
TIME_PREFIX = \"time\"\s*:\s*\"
TIME_FORMAT = %Y-%m-%dT%H:%M:%S%:z
MAX_TIMESTAMP_LOOKAHEAD = 32
TRUNCATE = 10000

[bb:web]
SHOULD_LINEMERGE = false
TIME_PREFIX = \[
TIME_FORMAT = %d/%b/%Y:%H:%M:%S %z
MAX_TIMESTAMP_LOOKAHEAD = 26
